### ISSUE TITLE
NotImplementedError in Admin::SiteMapsController#index

### ISSUE THREAD

**Issue by almonk** [withassociates/slices#104]
After running the install guide on a fresh Rails install, I get this while accessing /admin. The home page (/) appears to work fine in that it renders a blank page.

Ruby 2.0.0-p353 & Rails 3.2.16

<img width="751" alt="screen shot 2015-08-13 at 17 39 23" src="https://cloud.githubusercontent.com/assets/51724/9255599/5b93306c-41e2-11e5-8fe6-0f5ef1b6a16a.png">

**Comment by almonk** [comment]
Stack trace:

```

NotImplementedError (NotImplementedError):
  slices (1.0.3) lib/slices/i18n/backend.rb:15:in `available_locales'
  i18n (0.7.0) lib/i18n/backend/chain.rb:36:in `block in available_locales'
  i18n (0.7.0) lib/i18n/backend/chain.rb:36:in `map'
  i18n (0.7.0) lib/i18n/backend/chain.rb:36:in `available_locales'
  i18n (0.7.0) lib/i18n/config.rb:43:in `available_locales'
  i18n (0.7.0) lib/i18n/config.rb:49:in `available_locales_set'
  i18n (0.7.0) lib/i18n.rb:278:in `locale_available?'
  i18n (0.7.0) lib/i18n.rb:284:in `enforce_available_locales!'
  i18n (0.7.0) lib/i18n.rb:151:in `translate'
  devise (2.2.8) lib/devise/failure_app.rb:71:in `i18n_message'
  devise (2.2.8) lib/devise/failure_app.rb:60:in `redirect'
  devise (2.2.8) lib/devise/failure_app.rb:37:in `respond'
  actionpack (3.2.16) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.16) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.16) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.16) lib/action_controller/metal.rb:246:in `block in action'
  devise (2.2.8) lib/devise/failure_app.rb:20:in `call'
  devise (2.2.8) lib/devise/failure_app.rb:20:in `call'
  devise (2.2.8) lib/devise/delegator.rb:5:in `call'
  warden (1.2.3) lib/warden/manager.rb:130:in `call_failure_app'
  warden (1.2.3) lib/warden/manager.rb:116:in `process_unauthenticated'
  warden (1.2.3) lib/warden/manager.rb:47:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `_run__1889051479146239883__call__886242633345091459__callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.16) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.16) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.16) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.16) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.16) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.16) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.16) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.16) lib/action_dispatch/middleware/static.rb:63:in `call'
  railties (3.2.16) lib/rails/engine.rb:484:in `call'
  railties (3.2.16) lib/rails/application.rb:231:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.16) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'
  /Users/almonk/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /Users/almonk/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /Users/almonk/.rbenv/versions/2.0.0-p353/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by erino** [comment]
Can you try updating the version of Rails in your `Gemfile` to `gem 'rails', '~> 3.2.22'`

**Comment by almonk** [comment]
@erino Same error I'm afraid after Rails update & restart

**Comment by erino** [comment]
@almonk Ok, I've managed to recreate a fix the problem, can you add the following to your `Gemfile` 

`gem 'i18n', '~> 0.6.11'` then run `bundle update i18n` and restart

**Comment by almonk** [comment]
That was it! Cheers.
